# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embed-jobs.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10\x65mbed-jobs.proto\x12\x08services"\xdf\x01\n\x13\x41rticleNotification\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tarticleId\x18\x02 \x01(\t\x12\r\n\x05orgId\x18\x03 \x01(\x05\x12\x13\n\x0b\x63onnectorId\x18\x04 \x01(\x05\x12\x0e\n\x06source\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x12-\n\toperation\x18\x07 \x01(\x0e\x32\x1a.services.ArticleOperation\x12$\n\x08location\x18\x08 \x01(\x0b\x32\x12.services.Location\x12\r\n\x05jobId\x18\t \x01(\t"8\n\x08Location\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\x0e\n\x06region\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t*6\n\x10\x41rticleOperation\x12\n\n\x06\x43REATE\x10\x00\x12\n\n\x06UPDATE\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "embed_jobs_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_ARTICLEOPERATION"]._serialized_start = 314
    _globals["_ARTICLEOPERATION"]._serialized_end = 368
    _globals["_ARTICLENOTIFICATION"]._serialized_start = 31
    _globals["_ARTICLENOTIFICATION"]._serialized_end = 254
    _globals["_LOCATION"]._serialized_start = 256
    _globals["_LOCATION"]._serialized_end = 312
# @@protoc_insertion_point(module_scope)
